### ISSUE TITLE
Incorrect page rendering

### ISSUE THREAD

**Issue by xiaohongred** [pymupdf/PyMuPDF#3252]
### Description of the bug

`
doc = fitz.open('test.pdf')
page = doc[5]

pix = page.get_pixmap(dpi=1500) 
pix.save('fitz.png')
`

when i convert every page of a pdf file to a png image, i found some text overlap.
in pdf file , it like this:
<img width="253" alt="png1" src="https://github.com/pymupdf/PyMuPDF/assets/13983618/46ca7aba-2d73-435c-8efb-25e56de9ac10">

after convert to png image file:
![png2](https://github.com/pymupdf/PyMuPDF/assets/13983618/d57e7cda-9811-4b55-9096-4e802f3e0af5)

what i can do to solve this problem ?
thanks a lot if anyone can give some help

### How to reproduce the bug

`
doc = fitz.open('test.pdf')
page = doc[5]

pix = page.get_pixmap(dpi=1500) 
pix.save('fitz.png')
`

### PyMuPDF version

1.23.25

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
To reproduce, we need the problem page as a PDF.
Thanks.

**Comment by xiaohongred** [comment]
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/14556275/test.pdf)

use: 

doc = fitz.open('test.pdf')
page = doc[0]

pix = page.get_pixmap(dpi=1500)
pix.save('fitz.png')

Thanks

**Comment by JorjMcKie** [comment]
This is a problem located in the base library. I submitted an [issue](https://bugs.ghostscript.com/show_bug.cgi?id=707652) there.

**Comment by JorjMcKie** [comment]
This has been fixed to the extent possible in v1.24.2.
The main point is that the PDF contains fonts in error, therefore there are limits to how much can be done here.

**Comment by xiaohongred** [comment]
Thank you very much for your work.
I still encountered this issue in version 1.25.5, macOS system.
I found chrome browser can show this pdf correct, but macos preview has problem
<img width="1490" alt="Image" src="https://github.com/user-attachments/assets/108aa050-1e78-4545-bcf1-0e668173553b" />
