### ISSUE TITLE
Preparing metadata (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by marlonmp** [pymupdf/PyMuPDF#3281]
### Description of the bug

I was trying to install PyMuPDF 1.23.26 in a Python 3.12 (Alpine 3.19) container, and when I built the container pip throw me this error `Preparing metadata (pyproject.toml) did not run successfully`

### How to reproduce the bug

**Dockerfile**
```dockerfile
FROM python:3.12-alpine AS build-env

# set environment varibles
ENV LANG=es_CO.UTF-8
ENV LC_ALL=es_CO.UTF-8
ENV LC_CTYPE=es_CO.UTF8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=utf-8

RUN apk add --no-cache tzdata
ENV TZ America/Bogota


RUN apk --update --no-cache add \
    build-base \
    postgresql \
    postgresql-dev \
    libpq \
    jpeg-dev \
    zlib-dev \
    libffi-dev

ARG requirements

COPY ./requirements /tmp/requirements

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /tmp/requirements/develop.txt  
```
--- 
**Output**

The output is too long, so I attached it in this txt file [output.txt](https://github.com/pymupdf/PyMuPDF/files/14653037/output.txt)

### PyMuPDF version

1.23.26

### Operating system

Linux

### Python version

3.12

**Comment by apyrgio** [comment]
We've encountered the same issue and reported it pretty much at the same time :slightly_smiling_face:. Here's the underlying reason for the build failure: https://github.com/pymupdf/PyMuPDF/issues/3279#issuecomment-2007676568

**Comment by julian-smith-artifex-com** [comment]
Thanks to @apyrgio for the reference. I'll mark this as fixed in next release.

**Comment by julian-smith-artifex-com** [comment]
Fixed in 1.24.0.

**Comment by av1m** [comment]
Hello @julian-smith-artifex-com, i'm actually using the `1.24.5`, and i still have this problem.
I use `python:3.12-alpine`.
I'm currently blocked at this line : 
```
=> => #   Preparing metadata (pyproject.toml): started
```

**Comment by julian-smith-artifex-com** [comment]
Please attach the full output.

**Comment by av1m** [comment]
<details><summary>Code block on Mac Air M1</summary>
<pre>
Collecting pymupdf==1.24.5
  Downloading PyMuPDF-1.24.5.tar.gz (22.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.5/22.5 MB 33.5 MB/s eta 0:00:00
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: ### Starting.
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: __name__: 'setup'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: platform.platform(): 'Linux-6.5.11-linuxkit-aarch64-with'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: platform.python_version(): '3.12.4'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: sys.executable: '/usr/local/bin/python'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: CPU bits: 64 sys.maxsize=9223372036854775807
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: __file__: '/tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: os.getcwd(): '/tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: sys.argv (3):
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     0: '/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     1: 'prepare_metadata_for_build_wheel'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     2: '/tmp/tmp_ghp4f3d'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: os.environ (15):
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     GPG_KEY: '__hidden__'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     HOME: '/root'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     HOSTNAME: 'ce49cb77f5df'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     LANG: 'C.UTF-8'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PATH: '/tmp/pip-build-env-cmev6ykm/overlay/bin:/tmp/pip-build-env-cmev6ykm/normal/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PEP517_BACKEND_PATH: '/tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PEP517_BUILD_BACKEND: 'setup'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PIP_BUILD_TRACKER: '/tmp/pip-build-tracker-w5paz_ko'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PYTHONNOUSERSITE: '1'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PYTHONPATH: '/tmp/pip-build-env-cmev6ykm/site'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PYTHON_GET_PIP_SHA256: 'dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PYTHON_GET_PIP_URL: 'https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PYTHON_PIP_VERSION: '24.0'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     PYTHON_VERSION: '3.12.4'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py:     TERM: 'xterm'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: get_mupdf_internal(): out='dir' location=None sha=None
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: Download location='https://mupdf.com/downloads/archive/mupdf-1.24.2-source.tar.gz' local_tgz='mupdf-1.24.2-source.tar.gz' name='mupdf-1.24.2-source'
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: Downloading from location='https://mupdf.com/downloads/archive/mupdf-1.24.2-source.tar.gz' to local_tgz='mupdf-1.24.2-source.tar.gz'.
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: Extracting mupdf-1.24.2-source.tar.gz
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: Setting XCFLAGS and XCXXFLAGS to predefine TOFU_CJK_EXT.
      pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py: Building MuPDF by running: cd /tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/mupdf-1.24.2-source && XCFLAGS=-DTOFU_CJK_EXT XCXXFLAGS=-DTOFU_CJK_EXT /usr/local/bin/python ./scripts/mupdfwrap.py -d build/PyMuPDF-aarch64-shared-tesseract-release -b all && echo /tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/mupdf-1.24.2-source/build/PyMuPDF-aarch64-shared-tesseract-release: && ls -l /tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/mupdf-1.24.2-source/build/PyMuPDF-aarch64-shared-tesseract-release
      (+0.3s): -b: m: __main__.py:1613:build: Building libmupdf.so ...
      (+0.3s): -b: m: __main__.py:1217:_get_m_command: Setting -j to  multiprocessing.cpu_count()=8
      (+0.3s): -b: m: __main__.py:1615:build: running: cd /tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/mupdf-1.24.2-source && make -j 8 HAVE_GLUT=no HAVE_PTHREAD=yes verbose=yes shared=yes HAVE_LEPTONICA=yes HAVE_TESSERACT=yes build=release build_prefix=PyMuPDF-aarch64-shared-tesseract-
      (+0.3s): -b: m: __main__.py:1615:build: (+0.3s): -b: m: __main__.py:1615:build: /bin/sh: make: not found
      (+0.3s): -b: m: __main__.py:1615:build: (+0.3s): -b: m: __main__.py:1615:build:
      (+0.3s): -b: m: __main__.py:1615:build: [returned e=127]
      Traceback (most recent call last):
          scripts/mupdfwrap.py:6:<module>(): wrap.__main__.main()
          scripts/wrap/__main__.py:3089:main(): jlib.exception_info()
          ^except raise:
          scripts/wrap/__main__.py:3087:main(): main2()
          scripts/wrap/__main__.py:2481:main2(): build( build_dirs, swig_command, args, vs_upgrade, make_command)
          scripts/wrap/__main__.py:1615:build(): jlib.system( command, prefix=jlib.log_text(), out='log', verbose=1)
          scripts/jlib.py:1682:system(): raise Exception( message)
      Exception: Command failed: cd /tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/mupdf-1.24.2-source && make -j 8 HAVE_GLUT=no HAVE_PTHREAD=yes verbose=yes shared=yes HAVE_LEPTONICA=yes HAVE_TESSERACT=yes build=release build_prefix=PyMuPDF-aarch64-shared-tesseract-
      Traceback (most recent call last):
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/pipcl.py", line 642, in build_wheel
          items = self._call_fn_build(config_settings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/pipcl.py", line 812, in _call_fn_build
          ret = self.fn_build()
                ^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py", line 563, in build
          mupdf_build_dir = build_mupdf_unix( mupdf_local, env_extra, build_type)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/setup.py", line 810, in build_mupdf_unix
          subprocess.run( command, shell=True, check=True)
        File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'cd /tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/mupdf-1.24.2-source && XCFLAGS=-DTOFU_CJK_EXT XCXXFLAGS=-DTOFU_CJK_EXT /usr/local/bin/python ./scripts/mupdfwrap.py -d build/PyMuPDF-aarch64-shared-tesseract-release -b all && echo /tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/mupdf-1.24.2-source/build/PyMuPDF-aarch64-shared-tesseract-release: && ls -l /tmp/pip-install-ykhqh1n5/pymupdf_3d143c17a44f4d2cac8569f6d5e44bd7/mupdf-1.24.2-source/build/PyMuPDF-aarch64-shared-tesseract-release' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: pip install --upgrade pip


</pre>
</details> 


<details><summary>Code block on Google Cloud Shell</summary>
<pre>
Collecting pymupdf==1.24.5
  Downloading PyMuPDF-1.24.5.tar.gz (22.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.5/22.5 MB 33.5 MB/s eta 0:00:00
  Getting requirements to build wheel ... done
avi_mimoun@cloudshell:~ (meraki-syslog)$ 
avi_mimoun@cloudshell:~ (meraki-syslog)$ docker run -it python:3.12-alpine pip install pymupdf==1.24.5
Unable to find image 'python:3.12-alpine' locally
3.12-alpine: Pulling from library/python
ec99f8b99825: Pull complete 
a68bf89b0030: Pull complete 
dc4556e82255: Pull complete 
32e2ec03db6e: Pull complete 
eb2ccc024fc3: Pull complete 
Digest: sha256:dc095966439c68283a01dde5e5bc9819ba24b28037dddd64ea224bf7aafc0c82
Status: Downloaded newer image for python:3.12-alpine
Collecting pymupdf==1.24.5
  Downloading PyMuPDF-1.24.5.tar.gz (22.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.5/22.5 MB 21.4 MB/s eta 0:00:00
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: ### Starting.
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: __name__: 'setup'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: platform.platform(): 'Linux-6.1.85+-x86_64-with'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: platform.python_version(): '3.12.4'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: sys.executable: '/usr/local/bin/python'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: CPU bits: 64 sys.maxsize=9223372036854775807
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: __file__: '/tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: os.getcwd(): '/tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: sys.argv (3):
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     0: '/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     1: 'prepare_metadata_for_build_wheel'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     2: '/tmp/tmp_vw9s2_e'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: os.environ (15):
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     GPG_KEY: '__hidden__'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     HOME: '/root'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     HOSTNAME: 'b5bbea3e9dbb'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     LANG: 'C.UTF-8'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PATH: '/tmp/pip-build-env-_549tw2_/overlay/bin:/tmp/pip-build-env-_549tw2_/normal/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PEP517_BACKEND_PATH: '/tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PEP517_BUILD_BACKEND: 'setup'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PIP_BUILD_TRACKER: '/tmp/pip-build-tracker-wc5mxsu0'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PYTHONNOUSERSITE: '1'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PYTHONPATH: '/tmp/pip-build-env-_549tw2_/site'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PYTHON_GET_PIP_SHA256: 'dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PYTHON_GET_PIP_URL: 'https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PYTHON_PIP_VERSION: '24.0'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     PYTHON_VERSION: '3.12.4'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py:     TERM: 'xterm'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: get_mupdf_internal(): out='dir' location=None sha=None
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: Download location='https://mupdf.com/downloads/archive/mupdf-1.24.2-source.tar.gz' local_tgz='mupdf-1.24.2-source.tar.gz' name='mupdf-1.24.2-source'
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: Downloading from location='https://mupdf.com/downloads/archive/mupdf-1.24.2-source.tar.gz' to local_tgz='mupdf-1.24.2-source.tar.gz'.
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: Extracting mupdf-1.24.2-source.tar.gz
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: Setting XCFLAGS and XCXXFLAGS to predefine TOFU_CJK_EXT.
      pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py: Building MuPDF by running: cd /tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/mupdf-1.24.2-source && XCFLAGS=-DTOFU_CJK_EXT XCXXFLAGS=-DTOFU_CJK_EXT /usr/local/bin/python ./scripts/mupdfwrap.py -d build/PyMuPDF-x86_64-shared-tesseract-release -b all && echo /tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/mupdf-1.24.2-source/build/PyMuPDF-x86_64-shared-tesseract-release: && ls -l /tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/mupdf-1.24.2-source/build/PyMuPDF-x86_64-shared-tesseract-release
      (+0.4s): -b: m: __main__.py:1613:build: Building libmupdf.so ...
      (+0.4s): -b: m: __main__.py:1217:_get_m_command: Setting -j to  multiprocessing.cpu_count()=4
      (+0.4s): -b: m: __main__.py:1615:build: running: cd /tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/mupdf-1.24.2-source && make -j 4 HAVE_GLUT=no HAVE_PTHREAD=yes verbose=yes shared=yes HAVE_LEPTONICA=yes HAVE_TESSERACT=yes build=release build_prefix=PyMuPDF-x86_64-shared-tesseract-
      (+0.4s): -b: m: __main__.py:1615:build: (+0.4s): -b: m: __main__.py:1615:build: /bin/sh: make: not found
      (+0.4s): -b: m: __main__.py:1615:build: (+0.4s): -b: m: __main__.py:1615:build:
      (+0.4s): -b: m: __main__.py:1615:build: [returned e=127]
      Traceback (most recent call last):
          scripts/mupdfwrap.py:6:<module>(): wrap.__main__.main()
          scripts/wrap/__main__.py:3089:main(): jlib.exception_info()
          ^except raise:
          scripts/wrap/__main__.py:3087:main(): main2()
          scripts/wrap/__main__.py:2481:main2(): build( build_dirs, swig_command, args, vs_upgrade, make_command)
          scripts/wrap/__main__.py:1615:build(): jlib.system( command, prefix=jlib.log_text(), out='log', verbose=1)
          scripts/jlib.py:1682:system(): raise Exception( message)
      Exception: Command failed: cd /tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/mupdf-1.24.2-source && make -j 4 HAVE_GLUT=no HAVE_PTHREAD=yes verbose=yes shared=yes HAVE_LEPTONICA=yes HAVE_TESSERACT=yes build=release build_prefix=PyMuPDF-x86_64-shared-tesseract-
      Traceback (most recent call last):
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/pipcl.py", line 642, in build_wheel
          items = self._call_fn_build(config_settings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/pipcl.py", line 812, in _call_fn_build
          ret = self.fn_build()
                ^^^^^^^^^^^^^^^
        File "/tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py", line 563, in build
          mupdf_build_dir = build_mupdf_unix( mupdf_local, env_extra, build_type)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/setup.py", line 810, in build_mupdf_unix
          subprocess.run( command, shell=True, check=True)
        File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'cd /tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/mupdf-1.24.2-source && XCFLAGS=-DTOFU_CJK_EXT XCXXFLAGS=-DTOFU_CJK_EXT /usr/local/bin/python ./scripts/mupdfwrap.py -d build/PyMuPDF-x86_64-shared-tesseract-release -b all && echo /tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/mupdf-1.24.2-source/build/PyMuPDF-x86_64-shared-tesseract-release: && ls -l /tmp/pip-install-5aronp4y/pymupdf_8b1a9fa27cfd4e1192e89da6114b2d88/mupdf-1.24.2-source/build/PyMuPDF-x86_64-shared-tesseract-release' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: pip install --upgrade pip
</pre>
</details>

**Comment by julian-smith-artifex-com** [comment]
Both these have the same problem - you need to install `make`. You might also need to install other development tools such as C and C++ compilers.

> `(+0.3s): -b: m: main.py:1615:build: (+0.3s): -b: m: main.py:1615:build: /bin/sh: make: not found`

> `(+0.4s): -b: m: main.py:1615:build: (+0.4s): -b: m: main.py:1615:build: /bin/sh: make: not found`

I'm going to close this issue now. Please open a new issue if you run into more problems.
