### ISSUE TITLE
apply_redactions moves graphics

### ISSUE THREAD

**Issue by BeSaad** [pymupdf/PyMuPDF#3611]
### Description of the bug

Look into this pdf page
<img width="523" alt="Screenshot 2024-06-24 at 22 54 11" src="https://github.com/pymupdf/PyMuPDF/assets/74976706/60f54486-3f62-4a81-9445-2a5698a4efd9">

When I apply redaction using `page.apply_redactions()` (random rectangle) I end up with this
<img width="456" alt="Screenshot 2024-06-24 at 22 54 24" src="https://github.com/pymupdf/PyMuPDF/assets/74976706/c732c998-a2cc-46ed-8491-f1ac8845a2fa">

The grey rectangle is moved to the bottom left of the page (but the white text "Super lib..." remains there)

So I guess Its somehow similar to the issue about text being moved after redaction

### How to reproduce the bug

here the pdf file to test 
[issue.pdf](https://github.com/user-attachments/files/15959315/issue.pdf)

(the pdf is exported from overleaf/latex)

### PyMuPDF version

1.24.5

### Operating system

MacOS

### Python version

3.12

**Comment by JorjMcKie** [comment]
Fixed in version 1.24.6.

**Comment by raphaelbadawi** [comment]
Hello,

It seems the issue still happen on some pdf files.

[Resume not redacted.pdf](https://github.com/user-attachments/files/17747867/Resume.not.redacted.pdf)

[Resume redacted.pdf](https://github.com/user-attachments/files/17747866/Resume.redacted.pdf)
