### ISSUE TITLE
PyMuPDF Pro Incorrect Extraction of Chinese Content

### ISSUE THREAD

**Issue by maxyou2090** [pymupdf/PyMuPDF#3998]
### Description of the bug

PyMuPDF Pro extracts Chinese content inaccurately, resulting in mismatched text from the original document.

### How to reproduce the bug

Code Sample
```
import pymupdf.pro

pymupdf.pro.unlock()
doc = pymupdf.open("demo.doc")
for page in doc:
    print(page.get_text())
    break
```

Output
```
⼲东⼲州
广东广州
```

DOCX Content
```
广东广州
广东广州
```

DOCX File
[demo.doc.zip](https://github.com/user-attachments/files/17550821/demo.doc.zip)

### PyMuPDF version

1.24.12

### Operating system

MacOS

### Python version

3.10

**Comment by julian-smith-artifex-com** [comment]
This was fixed in PyMuPDFPro-1.24.12.

**Comment by maxyou2090** [comment]
> This was fixed in PyMuPDFPro-1.24.12.

What? When I submitted the issue, the version was 1.24.12. I just tested it again, and the same problem still exists.
