### ISSUE TITLE
delete_pages() does not accept a single int

### ISSUE THREAD

**Issue by JojoMueller** [pymupdf/PyMuPDF#4462]
### Description of the bug

document.delete_pages() should accept a single int positional parameter - called "Format 3" in documentation. But calling it with a single int parameter triggers an exception when trying to covert it to  a tuple with tuple(r). 

### How to reproduce the bug

call e.g. delete_pages(-1)

### PyMuPDF version

1.25.4

### Operating system

Windows

### Python version

3.13

**Comment by JorjMcKie** [comment]
Thanks for your report. Fix developed.

**Comment by julian-smith-artifex-com** [comment]
Fixed in PyMuPDF-1.26.3.

**Comment by JojoMueller** [comment]
Just installed and tested the fix. The command to reproduce the bug `delete_pages(-1)`, which is a valid "Format 3" statement, still doesn't work.  See: 
` if numbers[0] < 0 or numbers[-1] >= page_count:
            raise ValueError("bad page number(s)")`

**Comment by JorjMcKie** [comment]
> Just installed and tested the fix. The command to reproduce the bug `delete_pages(-1)`, which is a valid "Format 3" statement, still doesn't work. See: ` if numbers[0] < 0 or numbers[-1] >= page_count: raise ValueError("bad page number(s)")`

Thanks for the observation.~~We will prohibit negative numbers via documentation.~~

**Comment by julian-smith-artifex-com** [comment]
Fixed in PyMuPDF-1.26.4.
