### ISSUE TITLE
pymupdf4llm with pymupdfpro

### ISSUE THREAD

**Issue by mark3st** [pymupdf/PyMuPDF#4496]
I got pymupdf pro key and tried to pymupdf4llm.mark_down(example.hwpx)

Then I got runtime error. 

RuntimeError: code=7: cannot find entry Contents/Contents/header.xml

But this did not happen when I executed mark_down function with example.hwp file.

Have this happened to other people as well?
If it’s not, please share your solution.

Thank you for your support for hwp, hwpx files.

**Comment by JorjMcKie** [comment]
With the provided test file, the error can be reproduced like this:
```python
import pymupdf.pro

pymupdf.pro.unlock(key)
doc = pymupdf.open("test.hwpx")
print(doc.page_count)
```
The traceback:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(doc.page_count)
          ^^^^^^^^^^^^^^
  File "...\site-packages\pymupdf\__init__.py", line 5109, in page_count
    return self.page_count2(self)
           ~~~~~~~~~~~~~~~~^^^^^^
  File "...\site-packages\pymupdf\extra.py", line 135, in page_count_fz
    return _extra.page_count_fz(document)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
RuntimeError: code=7: cannot find entry Contents/Contents/header.xml
```

**Comment by JorjMcKie** [comment]
SmartOffice bug tracker link: https://bugs.ghostscript.com/show_bug.cgi?id=708522

**Comment by JorjMcKie** [comment]
The MuPDF team has identified and fixed the problem.
The fix will be part of one of the next PyMuPDF versions.

**Comment by julian-smith-artifex-com** [comment]
This was fixed in PyMuPDF-1.26.1 and PyMuPDFPro-1.26.1.

**Comment by mark3st** [comment]
> This was fixed in PyMuPDF-1.26.1 and PyMuPDFPro-1.26.1.

Thanks for your hard work.
it works with pymupdf4llm ver <=0.0.19 but it still doesn't work with the higher version.

the traceback:

```
❯ uv run test.py
PyMuPDFPro: Restricted Mode. Please visit https://pymupdf.io/try-pro to request your trial key.
Traceback (most recent call last):
  File "/Users/mark/mcp-rag/test.py", line 6, in <module>
    text = pymupdf4llm.to_markdown("a.hwpx")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/mcp-rag/.venv/lib/python3.11/site-packages/pymupdf4llm/helpers/pymupdf_rag.py", line 384, in to_markdown
    if doc.is_form_pdf or doc.has_annots():
                          ^^^^^^^^^^^^^^^^
  File "/Users/mark/mcp-rag/.venv/lib/python3.11/site-packages/pymupdf/utils.py", line 5127, in has_annots
    raise ValueError("is no PDF")
```

**Comment by julian-smith-artifex-com** [comment]
Ah the original problem is fixed but you're right that we now get this later exception with current pymupdf4llm.

**Comment by JorjMcKie** [comment]
Error fixed in PyMuPDF4LLM. Fix will be published with its version 0.0.27.

**Comment by julian-smith-artifex-com** [comment]
pymupdf4llm-0.0.27 has been out for a while, so closing this issue.
