### ISSUE TITLE
TextWriter - wrong font being used

### ISSUE THREAD

**Issue by jotaf98** [pymupdf/PyMuPDF#561]
## Describe the bug (mandatory)
`TextWriter`, when used repeatedly with 3 or more fonts, sometimes uses the wrong font, and prints out of bounds.

## To Reproduce (mandatory)
Here's a script that prints the same text with 3 fonts, in multiple panels:

```
import fitz

font1 = fitz.Font('tiro')
font2 = fitz.Font('cour')
font3 = fitz.Font('helv')

(b, s) = (10, 150)  # border and panel size
text = 'abcde fghij klmno pqrst uvwxyz'

doc = fitz.open()
page = doc.newPage()

panel = fitz.Rect((b, b), (s, s))

for _ in range(15):
  wr = fitz.TextWriter(page.rect)
  rect = fitz.Rect(panel)

  for font in [font1, font2, font3]:
    wr.fillTextbox(rect=rect, text=text, fontsize=12, font=font)
    rect.y0 = wr.lastPoint.y

  wr.writeText(page)

  panel.x0 += s + b
  panel.x1 += s + b
  if panel.x1 >= page.rect.x1:
    panel.x0 = b
    panel.x1 = s + b
    panel.y0 += s + b
    panel.y1 += s + b

doc.save('test.pdf')
```

## Expected behavior (optional)
The passed in fonts should be used in the specified order, and no text would be out of the specified rect.

## Screenshots (optional)
See screenshot and attached PDF (tested with SumatraPDF and Foxit Reader).
Compare the first group of text (top-left), with the group below it; according to the code they should look the same but don't.
![screen](https://user-images.githubusercontent.com/8715778/87856933-7a839d80-c91a-11ea-9476-84c0cbee4796.png)
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/4941966/test.pdf)

## Your configuration (mandatory)
 - Windows 10, 64 bits
 - Python 3.7.3, 64 bits
 - PyMuPDF 1.17.3, installed with pip (wheel)

**Comment by JorjMcKie** [comment]
Thanks for submitting this - issue confirmed.
There are two separate issues overlapping each othe:
1. As documented, the new ``TextWriter`` feature has issues with character spacing for mono-spaced fonts. This seems to be thecase fr all such fonts, and I so far have encountered only on mono font handled correctly: ``consola.ttf``. If you choose this one instead of Courier, you should be fine in that respect. I also have a little correction utiliy which makes other mono fonts show correct layouts for a given PDF, if you are interested.
2. The second part is my bad: in order to determine the next available fontname looking like ``Fnnn``, I am just increasing nnn, and ignoring the fact that ``F9 > F10`` (!!!) for example. This happens exactly in rectangle 4.

With  these corrections and a little massage of the layout, the page looks like this:
![grafik](https://user-images.githubusercontent.com/8290722/87861775-5c686e00-c917-11ea-8a1c-30fc6167da18.png)

This is the script producing it:
```python
import fitz

font1 = fitz.Font("tiro")
font2 = fitz.Font(fontfile="C:/Windows/Fonts/consolab.ttf")
font3 = fitz.Font("helv")
fonts = (font1, font2, font3)
text = "abcde fghij klmno pqrst uvwxyz"
fsize = 15

doc = fitz.open()
page = doc.newPage()

# lay out a table of 15 rectangles covering the page
cols = 3
rows = 5
table_rect = page.rect + (72, 72, -72, -72)  # go away from page corners
cells = fitz.make_table(rect=table_rect, cols=cols, rows=rows)

for i in range(rows):
    for j in range(cols):
        wr = fitz.TextWriter(page.rect)
        pos = None  # first text part starts at top-left
        for font in fonts:
            print(pos)
            wr.fillTextbox(cells[i][j],  # each cell is a rectangle
                text=text, pos=pos, fontsize=fsize, font=font)
            pos = wr.lastPoint + (5, 0) # next text part starts here
        wr.writeText(page)

doc.save(__file__.replace(".py", ".pdf"))
```

**Comment by JorjMcKie** [comment]
BTW I just found out, that the [Cascadia]() fonts also work correctly like Consolas does. This is a Microsoft font, which can be downloaded from [here](https://github.com/microsoft/cascadia-code/releases) and which works on all OS. It is permissively licensed under the SIL Open Font license.

**Comment by JorjMcKie** [comment]
Here is another suitable mono spaced font: [Fira Code](https://github.com/tonsky/FiraCode) from Mozilla.

**Comment by jotaf98** [comment]
Ah, that explains it!! That's great, thanks for looking into it.

The part relevant for my code is actually the second (looking for the wrong font name). I guess the monospace problem came up by accident.

**Comment by JorjMcKie** [comment]
> I guess the monospace problem came up by accident.

Yes, as I mentioned: you have had two problems. Like my grandma always said: one can have lice **and** mice!
The mono space font issue does exist however. I am still investigating and I also have sent a bug report to MuPDF (Artifex) - without reaction so far after several weeks.
So I would recommend to not using Courier for mono text output.
However, as mentioned I have built a little repair utility, which digs its way through the generated text and corrects it. It will be part of the next PyMuPDF version. Actually a shame that it is needed (or I am too dumb to find the right trick).
It would be invoked like this ``fitz.repair_mono_font(page, font)`` where ``font`` is a ``fitz.Font`` with that misbehaviour. It does work for Courier and some handful of other problem fonts (DejaVu Mono, Noto Mono, Courier, ...).

I you need a solution with some urgency, I can send you a pre-version.

**Comment by jotaf98** [comment]
That's alright, perhaps a brief note (pointing to the repair function) in the docs would help, but otherwise I wouldn't fret too much if it's upstream.

It's not urgent as this is more of a hobby project, and I worked around it in a project-specific way.

Looking forward to the release that squashes one or two pests, when it's ready!

**Comment by JorjMcKie** [comment]
Just thought about your issue:
You can avoid the problem right away if you take `TextWriter` creation and writing to the page out of the loop!
That way, only **_one_** frontname reference per font will ever be created on the page and that "overflow" won't occur (here).
And of course there is some performance gain dealing with just textwriter instead of 15.

**Comment by JorjMcKie** [comment]
Resolved by v1.17.4, which is just uploading to PyPI.
Note:
I also found a way to automatically deal with the mono-spaced fonts: these should now all be correct without needing extra fiddling around with them.

**Comment by jotaf98** [comment]
Thanks once again! I hate to re-open this, but even with the update the problem remains.

I don't mean that it doesn't fix the code I posted above -- it does! -- however a minor change brings back the bad behavior. Here it is:

```
import fitz

font1 = fitz.Font('tiro')
font2 = fitz.Font('cour')
font3 = fitz.Font('helv')

(b, s) = (10, 150)  # border and panel size
text = 'abcde fghij klmno pqrst uvwxyz'

doc = fitz.open()
page = doc.newPage()

panel = fitz.Rect((b, b), (s, s))

for i in range(15):
  wr = fitz.TextWriter(page.rect)
  rect = fitz.Rect(panel)

  wr.append(rect.bl, 'Testing', fontsize=14, font=[font1, font2, font3][i % 3])  # NEW BIT

  for font in [font1, font2, font3]:
    wr.fillTextbox(rect=rect, text=text, fontsize=12, font=font)
    rect.y0 = wr.lastPoint.y

  wr.writeText(page)

  panel.x0 += s + b
  panel.x1 += s + b
  if panel.x1 >= page.rect.x1:
    panel.x0 = b
    panel.x1 = s + b
    panel.y0 += s + b
    panel.y1 += s + b

doc.save('test.pdf')
```

Mixing `fillTextBox` and `append` (by adding the line I marked above) seems to result in the same bug showing up again.

As a separate quick question, you mentioned that reusing the `TextWriter` should be more performant; is there any way to do this but writing different text? (In these contrived examples, we write the same words over and over again, but in real applications the text is usually different.)

**Comment by JorjMcKie** [comment]
> As a separate quick question, you mentioned that reusing the TextWriter should be more performant; is there any way to do this but writing different text? (In these contrived examples, we write the same words over and over again, but in real applications the text is usually different.)

Let me react to this one first:
If you take out text writer creation and `writeText` out of the loop, your example works correctly and is also more performant. It also should be no problem adding whatever (different) text in each loop.

```python
doc = fitz.open()
page = doc.newPage()

panel = fitz.Rect((b, b), (s, s))
wr = fitz.TextWriter(page.rect)

for i in range(15):
    rect = fitz.Rect(panel)

    wr.append(
        rect.bl, "Testing", fontsize=14, font=[font1, font2, font3][i % 3]
    )  # NEW BIT

    for font in [font1, font2, font3]:
        wr.fillTextbox(rect=rect, text=text, fontsize=12, font=font)
        rect.y0 = wr.lastPoint.y

    panel.x0 += s + b
    panel.x1 += s + b
    if panel.x1 >= page.rect.x1:
        panel.x0 = b
        panel.x1 = s + b
        panel.y0 += s + b
        panel.y1 += s + b

wr.writeText(page)

doc.save("test.pdf")
```

Haven't understood yet, why your original example fails ...

**Comment by JorjMcKie** [comment]
> Haven't understood yet, why your original example fails ...

Now I have! Embarrassingly, there was another major error in my code 🙄.
Well, this is now corrected and works wonderfully with your example code. So again thanks a lot for submitting this freaky example!

Some background on that error maybe:
The MuPDF function behind `writeText` always generates font references `/F0`, `/F1`, ..., always starting with `/F0` for each function call.  It doesn't care, which fonts may already exist for the page. So I need to intercept that, look at the page's highest number `n` for which there already exists a font named `/F<n>`. Then rename every font `/F<m>` in `TextWriter` to `/F<m+n+1>`. At this point, I (1) forgot the `+1`, and (2) falsely assumed that fonts in `TextWriter` are being named ascendingly ... they are **not**!

**Comment by JorjMcKie** [comment]
Here is a new pre-version:

[PyMuPDF-1.17.5-cp37-cp37m-win_amd64.zip](https://github.com/pymupdf/PyMuPDF/files/5034402/PyMuPDF-1.17.5-cp37-cp37m-win_amd64.zip)

Change the extension to `whl` and execute `python -m pip install -U PyMuPDF-1.17.5-cp37-cp37m-win_amd64.whl`.

**Comment by jotaf98** [comment]
That's great, thank you! Good find. I had no idea the font handling was so intricate.

Anyway this only happened once my program reached a certain level of complexity (as you see multiple factors were needed), so it was a bit tricky to isolate into a small script -- I hope it helped :)

As for my question about reusing `TextWriter`, you're absolutely right that I can call `writeText` only once at the very end. It would be more convenient to have each iteration be self-contained (since in my application each iteration is isolated into a function), but I can certainly work around it! Thanks for the suggestion.

**Comment by jotaf98** [comment]
Tested the fix, it works like a charm!

**Comment by JorjMcKie** [comment]
> As for my question about reusing TextWriter, you're absolutely right that I can call writeText only once at the very end. It would be **_more convenient to have each iteration be self-contained_** (since in my application each iteration is isolated into a function), but I can certainly work around it! Thanks for the suggestion.

Don't get me wrong - you definitely can do that (now 😎). The text writer will then live within that scope only and that's about it. As I wrote: there is some overhead and some file size increase, but arguably not much and not enough justification for a higher program complexity.
It is not possible to "empty" a text writer again for later re-use.

> was a bit tricky to isolate into a small script -- I hope it helped :)

It definitely did!!! Without it  - who knows when I would have stumbled over those bugs. Thanks again.
